# Generated by Django 4.0.4 on 2022-07-27 20:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segundaunidadefuncional',
            name='obs_imitacao_de_gestos',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações referente à estruturação rítmica'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='desenho_figura_humana',
            field=models.IntegerField(blank=True, help_text='Pontuação de 0 á 43', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51)], verbose_name='Desenho da figura humana'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 27), verbose_name='Data de Avaliação'),
        ),
    ]
