# Generated by Django 4.0.4 on 2022-07-28 18:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_segundaunidadefuncional_obs_imitacao_de_gestos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='desenho_figura_humana',
            field=models.IntegerField(blank=True, help_text='Pontuação de 0 á 51', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(51)], verbose_name='Desenho da figura humana'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.CreateModel(
            name='Conclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(default=datetime.date(2022, 7, 28), verbose_name='Data da Conclusão')),
                ('psico_afetivo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Aspectos Psico-Afetivos')),
                ('psico_cognitivo', models.TextField(blank=True, max_length=500, null=True, verbose_name='Aspectos Psico-Cognitivos')),
                ('tonicidade', models.TextField(blank=True, max_length=500, null=True, verbose_name='Tonicidade')),
                ('equilibracao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Equilibração')),
                ('esquema_imagem_corporal', models.TextField(blank=True, max_length=500, null=True, verbose_name='Esquema e Imagem Corporal')),
                ('lateralizacao', models.TextField(blank=True, max_length=500, null=True, verbose_name='Lateralização')),
                ('estruturacao_espaco_temporal', models.TextField(blank=True, max_length=500, null=True, verbose_name='Estruturação Espaço-Temporal')),
                ('praxia_global', models.TextField(blank=True, max_length=500, null=True, verbose_name='Praxia Global')),
                ('praxia_fina', models.TextField(blank=True, max_length=500, null=True, verbose_name='Praxia Fina')),
                ('grafomotricidade', models.TextField(blank=True, max_length=500, null=True, verbose_name='Grafomotricidade')),
                ('encaminhamento', models.TextField(blank=True, max_length=500, null=True, verbose_name='Encaminhamento')),
                ('prognostico', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Prognóstico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', verbose_name='Paciente')),
            ],
            options={
                'db_table': 'conclusao',
            },
        ),
    ]
