# Generated by Django 4.1 on 2022-09-28 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_remove_desenhofigurahumana_desenho_figura_humana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', unique=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='data_conclusao',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data da Conclusão'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paciente.paciente', unique=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 28), verbose_name='Data de Avaliação'),
        ),
    ]
