# Generated by Django 4.1 on 2022-09-30 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_deletado_alter_anamnese_data_anamnese_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='deletado',
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='data_conclusao',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data da Conclusão'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 9, 30), verbose_name='Data de Avaliação'),
        ),
    ]
