# Generated by Django 4.1 on 2022-09-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_remove_paciente_deletado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', unique=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', unique=True, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente', verbose_name='Paciente'),
        ),
    ]
