# Generated by Django 4.1 on 2022-10-04 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_alter_anamnese_paciente_alter_conclusao_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='data_conclusao',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data da Conclusão'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf_responsavel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone do Responsável'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 4), verbose_name='Data de Avaliação'),
        ),
    ]
