# Generated by Django 4.1 on 2022-10-05 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0010_alter_conclusao_id_alter_desenhofigurahumana_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnese',
            name='data_anamnese',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data de Anamnese'),
        ),
        migrations.AlterField(
            model_name='conclusao',
            name='data_conclusao',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data da Conclusão'),
        ),
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='primeiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data de Avaliação'),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='data_avaliacao',
            field=models.DateField(default=datetime.date(2022, 10, 5), verbose_name='Data de Avaliação'),
        ),
    ]
