# Generated by Django 4.1 on 2022-10-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_alter_conclusao_id_alter_desenhofigurahumana_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desenhofigurahumana',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='segundaunidadefuncional',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='terceiraunidadefuncional',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
